Mbeddr compilation error: reflective call to deleted private field
Partly revert commit 740b0ed6284c1e0ffdf171ca137af123e4b1e086 for now.
Should provide some extension possibility, to avoid this reflection calls.