MPS platform: fix startup with limited classpath
NoClassDefFoundError loading PlatformBase class from ConvertToBinaryTask due to missing MPSGenerator et al.